site_name: Pineapple SMP Wiki
nav:
  - Home: index.md
  - PSMP Info: info.md
  - Nations: nations.md
  - Significant Figures: figures.md
  - Past Servers: history.md
  - Lore: lore.md
  - Links: links.md
theme: material